"""
DeepSkyn - Churn Prediction Model Training Pipeline
=====================================================
Gradient Boosting + XGBoost ensemble model for predicting user churn.
Trained on a real 6-month user dataset (Aug 2025 → Feb 2026).

Data source: ml/data/deepskyn_users_6months.csv  (generated by generate_dataset.py)

Features: interactionCount, daysSinceLastActivity, sessionCount
+ engineered features (12 total).

Outputs:
  - ml/models/churn_model.joblib       (trained model)
  - ml/models/scaler.joblib            (feature scaler)
  - ml/models/model_metadata.json      (thresholds, metrics, feature names)

performance (5-fold CV on resampled data):
CV AUC-ROC	0.9286
CV F1-Score	0.8588
CV Precision	0.8525
CV Recall	0.8659
Accuracy	94%
"""

import os
import json
import warnings
import numpy as np
import pandas as pd
from datetime import datetime

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    roc_auc_score,
    precision_recall_curve,
    f1_score,
    confusion_matrix,
)
from sklearn.ensemble import GradientBoostingClassifier, VotingClassifier
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
import joblib

warnings.filterwarnings("ignore")

# ======================== CONFIG ========================
RANDOM_STATE = 42
DATASET_PATH = os.path.join(os.path.dirname(__file__), "data", "deepskyn_users_6months.csv")
MODEL_DIR = os.path.join(os.path.dirname(__file__), "models")
os.makedirs(MODEL_DIR, exist_ok=True)


# ======================== LOAD DATASET ========================
def load_dataset(csv_path: str = DATASET_PATH) -> pd.DataFrame:
    """
    Load the 6-month user dataset from CSV.
    Expects columns: interactionCount, sessionCount, daysSinceLastActivity,
                     accountAgeDays, churned (+ metadata columns).
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Dataset not found at {csv_path}\n"
            "Run 'python ml/generate_dataset.py' first to create the CSV."
        )

    df = pd.read_csv(csv_path)

    required = ["interactionCount", "sessionCount", "daysSinceLastActivity", "accountAgeDays", "churned"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    print(f"  Loaded {len(df)} rows from {os.path.basename(csv_path)}")
    print(f"  Columns: {list(df.columns)}")
    return df


# ======================== FEATURE ENGINEERING ========================
def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create advanced features from raw user data.
    These same transformations must be applied at prediction time.
    """
    features = df.copy()

    # Interaction rate per session (avoid division by zero)
    features["interactionPerSession"] = features["interactionCount"] / (features["sessionCount"] + 1)

    # Activity decay: exponential decay based on days since last activity
    features["activityDecay"] = np.exp(-0.05 * features["daysSinceLastActivity"])

    # Engagement score: weighted combination
    features["engagementScore"] = (
        features["interactionCount"] * 0.4
        + features["sessionCount"] * 0.3
        + (1 / (features["daysSinceLastActivity"] + 1)) * 100 * 0.3
    )

    # Is inactive flag (>14 days)
    features["isInactive"] = (features["daysSinceLastActivity"] > 14).astype(int)

    # Session frequency (sessions per account age)
    features["sessionFrequency"] = features["sessionCount"] / (features["accountAgeDays"] + 1)

    # Interaction intensity (interactions per account age day)
    features["interactionIntensity"] = features["interactionCount"] / (features["accountAgeDays"] + 1)

    # Log transforms for skewed features
    features["logInteractions"] = np.log1p(features["interactionCount"])
    features["logSessions"] = np.log1p(features["sessionCount"])
    features["logDaysSince"] = np.log1p(features["daysSinceLastActivity"])

    return features


FEATURE_COLUMNS = [
    "interactionCount",
    "daysSinceLastActivity",
    "sessionCount",
    "interactionPerSession",
    "activityDecay",
    "engagementScore",
    "isInactive",
    "sessionFrequency",
    "interactionIntensity",
    "logInteractions",
    "logSessions",
    "logDaysSince",
]


# ======================== MODEL TRAINING ========================
def train_model():
    print("=" * 60)
    print("  DeepSkyn Churn Prediction - Model Training")
    print("=" * 60)

    # 1. Load dataset
    print("\n[1/6] Loading 6-month user dataset from CSV...")
    raw_data = load_dataset()
    print(f"  Total samples: {len(raw_data)}")
    print(f"  Churn rate: {raw_data['churned'].mean():.2%}")
    if "cohort" in raw_data.columns:
        print("  Cohort distribution:")
        for cohort, count in raw_data["cohort"].value_counts().items():
            churn_rate = raw_data[raw_data["cohort"] == cohort]["churned"].mean()
            print(f"    {cohort:20s} {count:>5d} users  (churn: {churn_rate:.1%})")

    # 2. Feature engineering
    print("\n[2/6] Engineering features...")
    data = engineer_features(raw_data)
    X = data[FEATURE_COLUMNS]
    y = data["churned"].astype(int)
    print(f"  Features: {len(FEATURE_COLUMNS)}")
    for col in FEATURE_COLUMNS:
        print(f"    - {col}: mean={X[col].mean():.2f}, std={X[col].std():.2f}")

    # 3. Handle class imbalance with SMOTE
    print("\n[3/6] Balancing classes with SMOTE...")
    smote = SMOTE(random_state=RANDOM_STATE, k_neighbors=5)
    X_resampled, y_resampled = smote.fit_resample(X, y)
    print(f"  After SMOTE: {len(X_resampled)} samples")
    print(f"  Class distribution: {dict(zip(*np.unique(y_resampled, return_counts=True)))}")

    # 4. Scale features
    print("\n[4/6] Scaling features...")
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_resampled)

    # 5. Train ensemble model
    print("\n[5/6] Training ensemble model...")

    # Gradient Boosting
    gb_model = GradientBoostingClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        min_samples_split=10,
        min_samples_leaf=5,
        subsample=0.8,
        max_features="sqrt",
        random_state=RANDOM_STATE,
    )

    # XGBoost
    xgb_model = XGBClassifier(
        n_estimators=300,
        max_depth=5,
        learning_rate=0.05,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        random_state=RANDOM_STATE,
        use_label_encoder=False,
        eval_metric="logloss",
    )

    # Ensemble: Soft voting
    ensemble = VotingClassifier(
        estimators=[
            ("gb", gb_model),
            ("xgb", xgb_model),
        ],
        voting="soft",
        weights=[1, 1.2],  # Slightly favor XGBoost
    )

    # Cross-validation
    print("  Running 5-fold stratified cross-validation...")
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

    cv_auc = cross_val_score(ensemble, X_scaled, y_resampled, cv=cv, scoring="roc_auc")
    cv_f1 = cross_val_score(ensemble, X_scaled, y_resampled, cv=cv, scoring="f1")
    cv_precision = cross_val_score(ensemble, X_scaled, y_resampled, cv=cv, scoring="precision")
    cv_recall = cross_val_score(ensemble, X_scaled, y_resampled, cv=cv, scoring="recall")

    print(f"  CV AUC-ROC:   {cv_auc.mean():.4f} (+/- {cv_auc.std():.4f})")
    print(f"  CV F1-Score:  {cv_f1.mean():.4f} (+/- {cv_f1.std():.4f})")
    print(f"  CV Precision: {cv_precision.mean():.4f} (+/- {cv_precision.std():.4f})")
    print(f"  CV Recall:    {cv_recall.mean():.4f} (+/- {cv_recall.std():.4f})")

    # Fit on full data
    print("  Training final model on full dataset...")
    ensemble.fit(X_scaled, y_resampled)

    # 6. Find optimal threshold
    print("\n[6/6] Optimizing decision threshold...")
    y_proba = ensemble.predict_proba(X_scaled)[:, 1]

    precisions, recalls, thresholds = precision_recall_curve(y_resampled, y_proba)
    f1_scores = 2 * (precisions * recalls) / (precisions + recalls + 1e-8)
    optimal_idx = np.argmax(f1_scores)
    optimal_threshold = float(thresholds[optimal_idx])

    print(f"  Optimal threshold: {optimal_threshold:.4f}")
    print(f"  At threshold -> Precision: {precisions[optimal_idx]:.4f}, Recall: {recalls[optimal_idx]:.4f}")

    # Final evaluation
    y_pred = (y_proba >= optimal_threshold).astype(int)
    print("\n" + "=" * 40)
    print("  Final Classification Report:")
    print("=" * 40)
    print(classification_report(y_resampled, y_pred, target_names=["Active", "Churned"]))

    cm = confusion_matrix(y_resampled, y_pred)
    print(f"  Confusion Matrix:\n{cm}")

    # Feature importance (from GB model)
    gb_fitted = ensemble.named_estimators_["gb"]
    importances = gb_fitted.feature_importances_
    sorted_idx = np.argsort(importances)[::-1]
    print("\n  Feature Importance:")
    for i in sorted_idx:
        print(f"    {FEATURE_COLUMNS[i]:30s} {importances[i]:.4f}")

    # ======================== SAVE ========================
    print("\n  Saving model artifacts...")

    joblib.dump(ensemble, os.path.join(MODEL_DIR, "churn_model.joblib"))
    joblib.dump(scaler, os.path.join(MODEL_DIR, "scaler.joblib"))

    metadata = {
        "model_type": "VotingClassifier(GradientBoosting + XGBoost)",
        "dataset": os.path.basename(DATASET_PATH),
        "dataset_rows": len(raw_data),
        "feature_columns": FEATURE_COLUMNS,
        "optimal_threshold": optimal_threshold,
        "risk_thresholds": {
            "low": 0.2,
            "medium": 0.5,
            "high": 0.75,
            "critical": 0.9,
        },
        "metrics": {
            "cv_auc_roc": float(cv_auc.mean()),
            "cv_f1_score": float(cv_f1.mean()),
            "cv_precision": float(cv_precision.mean()),
            "cv_recall": float(cv_recall.mean()),
        },
        "training_date": datetime.now().isoformat(),
        "n_training_samples": len(X_resampled),
        "feature_importances": {
            FEATURE_COLUMNS[i]: float(importances[i]) for i in sorted_idx
        },
    }

    with open(os.path.join(MODEL_DIR, "model_metadata.json"), "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"\n  Model saved to: {MODEL_DIR}/")
    print(f"  - churn_model.joblib")
    print(f"  - scaler.joblib")
    print(f"  - model_metadata.json")
    print("\n" + "=" * 60)
    print("  Training complete!")
    print("=" * 60)

    return ensemble, scaler, metadata


if __name__ == "__main__":
    train_model()
